### ISSUE TITLE
Package scanner for entity classes

### ISSUE THREAD

**Issue by trainings** [orientechnologies/spring-data-orientdb#17]

**Comment by saljuama** [comment]
I'll get started on this one, but i'm not sure in which module it should live, I'm assuming the commons one, but I prefeer to ask just in case.

**Comment by saljuama** [comment]
If the PR doesn't meet the criteria of what you've expected, could you at least give any reason why? That way i can update it accordingly... either that, or this project is dead.

**Comment by saljuama** [comment]
Performed another PR 10 days ago for this issue, still awaiting for feedback.

**Comment by saljuama** [comment]
As you commented in this PR comments [here](https://github.com/orientechnologies/spring-data-orientdb/pull/32)

>  I like **@Entity** better, or another approach could be using something like **@Vertex** and **@Edge**. I'm going to merge this, but I'm open to consider using of vertex/edge annotation if you think it's a good idea.

I've been working with the Graph API mostly, and it clearly differentiates between vertices and edges, as you can see in this section of the documentation: [Working with Vertices and Edges](http://orientdb.com/docs/last/Graph-Database-Tinkerpop.html#working-with-vertices-and-edges). 

In order to implement the mappings behind the scenes, a mechanism to differentiate edges and vertices in the Java classes the users will be using is required, and doing so through annotations is just one option, and i think it is the appropiate one for several reasons, mainly the following ones: 

 - Makes the code very readable
 - Following the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), users coming from other spring data modules, or from HibernateJPA, would most likely expect to configure their mappings with annotations.
 - The use of other mechanisms, like, including a field in the class, extending from a base class, forcing certain package hierarchy, or others that I can't think of right now, are less flexible, and include more boilerplate code, which goes against Spring Data principles.

That being said, either using **@Vertex** and **@Edge**, or extending the **@Entity** with a field to indicate the type ( example: **@Entity(type=EntityType.VERTEX)** ), being the first one the prefered, as it is simpler and more expressive in my opinion, is a good idea.

**Comment by lvca** [comment]
I agree that having @Vertex and @Edge would be better.

**Comment by saljuama** [comment]
Created a new PR with the changes

**Comment by saljuama** [comment]
what else would you think it is needed to close this issue? more tests?

**Comment by lvca** [comment]
I'd say it's ok, closing. Thanks so much.
